version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./data:/mosquitto/data"
      - "./logs:/mosquitto/log"
    restart: always
  data-service:
    build: ../sps-dev-board-mqtt-data-service
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mqtt